import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

import Header from '../components/header';
import { ThemeProvider } from '../components/theme-provider';
import Footer from '../components/footer';

import './globals.css';
import 'highlight.js/styles/base16/tomorrow-night.css';

const notoSansKR = Noto_Sans_KR({
  display: 'swap',
  variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: "Laffee's Blogu",
  description: 'Generated by Next.js + Sanity',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSansKR.variable} antialiased min-h-screen font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="w-full max-w-screen-xl px-4 py-6 mt-16 mx-auto">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
